image:
  file: .gitpod.Dockerfile

tasks:
  - command: >
      export CMAKE_PREFIX=/opt/conda
  - init: chmod +x envconfig.sh &&
      ./envconfig.sh

vscode:
  extensions:
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==
    - cschlosser.doxdocgen@0.5.2:SsSNhKMGwp5iVRhI1fnHVA==
